//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalPam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsignacionOrganizacion
    {
        public int IDBecario { get; set; }
        public Nullable<int> IDOrganizacion { get; set; }
        public Nullable<int> Horas { get; set; }
    
        public virtual Becario Becario { get; set; }
        public virtual Organizacion Organizacion { get; set; }
    }
}
