//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalPam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Becario
    {
        public Becario()
        {
            this.Pagoes = new HashSet<Pago>();
            this.RegistroPagoes = new HashSet<RegistroPago>();
            this.ServicioBecadoes = new HashSet<ServicioBecado>();
        }
    
        public int IDBecario { get; set; }
        public int IDTutor { get; set; }
        public int IDCategoria { get; set; }
        public int IDEscuela { get; set; }
        public string Nombre { get; set; }
        public string ApellidoP { get; set; }
        public string ApellidoM { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string GradoEscolar { get; set; }
        public decimal Promedio { get; set; }
        public byte[] Foto { get; set; }
    
        public virtual AsignacionOrganizacion AsignacionOrganizacion { get; set; }
        public virtual Categoria Categoria { get; set; }
        public virtual Escuela Escuela { get; set; }
        public virtual Tutor Tutor { get; set; }
        public virtual ICollection<Pago> Pagoes { get; set; }
        public virtual ICollection<RegistroPago> RegistroPagoes { get; set; }
        public virtual ICollection<ServicioBecado> ServicioBecadoes { get; set; }
    }
}
