//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalPam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categoria
    {
        public Categoria()
        {
            this.Becarios = new HashSet<Becario>();
        }
    
        public int IDCategoria { get; set; }
        public string ClaveCat { get; set; }
        public string Descripcion { get; set; }
        public decimal Monto { get; set; }
    
        public virtual ICollection<Becario> Becarios { get; set; }
    }
}
