//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalPam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Escuela
    {
        public Escuela()
        {
            this.Becarios = new HashSet<Becario>();
        }
    
        public int IDEscuela { get; set; }
        public string Escuela1 { get; set; }
        public string Direccion { get; set; }
        public int Telefono { get; set; }
    
        public virtual ICollection<Becario> Becarios { get; set; }
    }
}
