//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalPam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organizacion
    {
        public Organizacion()
        {
            this.AsignacionOrganizacions = new HashSet<AsignacionOrganizacion>();
            this.ServicioBecadoes = new HashSet<ServicioBecado>();
        }
    
        public int IDOrg { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public int Telefono { get; set; }
        public int Celular { get; set; }
    
        public virtual ICollection<AsignacionOrganizacion> AsignacionOrganizacions { get; set; }
        public virtual ICollection<ServicioBecado> ServicioBecadoes { get; set; }
    }
}
