//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalPam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int IDPago { get; set; }
        public Nullable<decimal> Monto1 { get; set; }
        public Nullable<decimal> Monto2 { get; set; }
        public Nullable<decimal> Monto3 { get; set; }
        public Nullable<decimal> Monto4 { get; set; }
        public Nullable<decimal> Monto5 { get; set; }
        public Nullable<int> NumeroParcialidades { get; set; }
        public decimal MontoTotal { get; set; }
        public Nullable<decimal> MontoParcialidad { get; set; }
        public int BecadoID { get; set; }
    
        public virtual Becario Becario { get; set; }
    }
}
