//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalPam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroPago
    {
        public int IDRegistroPago { get; set; }
        public Nullable<int> IDBecado { get; set; }
        public string ClaveCat { get; set; }
        public Nullable<bool> Pago1 { get; set; }
        public Nullable<System.DateTime> FechaPago1 { get; set; }
        public Nullable<bool> Pago2 { get; set; }
        public Nullable<System.DateTime> FechaPago2 { get; set; }
        public Nullable<bool> Pago3 { get; set; }
        public Nullable<System.DateTime> FechaPago3 { get; set; }
        public Nullable<bool> Pago4 { get; set; }
        public Nullable<System.DateTime> FechaPago4 { get; set; }
        public Nullable<bool> Pago5 { get; set; }
        public Nullable<System.DateTime> FechaPago5 { get; set; }
    
        public virtual Becario Becario { get; set; }
    }
}
