//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalPam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicioBecado
    {
        public int IDServicio { get; set; }
        public int IDOrg { get; set; }
        public int IDBecado { get; set; }
        public string Dias { get; set; }
        public System.TimeSpan HorarioInicio { get; set; }
        public System.TimeSpan HorarioFin { get; set; }
        public string Actividades { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
    
        public virtual Becario Becario { get; set; }
        public virtual Organizacion Organizacion { get; set; }
    }
}
