//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalPam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tutor
    {
        public Tutor()
        {
            this.Becarios = new HashSet<Becario>();
        }
    
        public int IDTutor { get; set; }
        public string Nombre { get; set; }
        public string ApellidoP { get; set; }
        public string ApellidoM { get; set; }
        public string DomicilioCasa { get; set; }
        public string DomicilioTrabajo { get; set; }
        public string Correo { get; set; }
        public string Puesto { get; set; }
        public int TelefonoCasa { get; set; }
        public int TelefonoTrabajo { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFinal { get; set; }
    
        public virtual ICollection<Becario> Becarios { get; set; }
    }
}
